---
title: "LBB_RM_House"
author: "Amalia Purieka"
date: "1/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(car)
library(plotly)
library(data.table)
library(GGally)
library(tidymodels)
library(caret)
library(scales)
library(lmtest)

options(scipen = 100, max.print = 1e+06)
```

### Data

```{r}
datahouse <- read.csv("data_input/house_data.csv")

rmarkdown::paged_table(datahouse)
```
This datahouse has 9 columns and 21613 rows

```{r}
str(datahouse)
```

```{r}
table(datahouse$bathrooms)
table(datahouse$bedrooms)
table(datahouse$floors)
table(datahouse$waterfront)
table(datahouse$grade)
table(datahouse$yr_built)
```

```{r}
hist(datahouse$bathrooms)
hist(datahouse$bedrooms)
hist(datahouse$floors)
hist(datahouse$waterfront)
hist(datahouse$grade)
hist(datahouse$yr_built)
```
```{r}
# ggpairs(datahouse)
ggcorr(datahouse, label = T)
```

```{r}
# Model
model_datahouse <- lm(price ~ ., datahouse)
summary(model_datahouse)
```

```{r}
model_step_dh <- step(model_datahouse, direction = "both")
summary(model_step_dh)
```

